name: Build and Push

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build backend image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app-backend ./server

            - name: Build Frontend Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app-frontend ./client/my-react-app

            - name: Push both images to DockerHub
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app-backend
                docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app-frontend 